# Change these first
owner: sixstartech # Your GitHub organization or username, where this repository lives
repo: upptime-str # The name of this repository

sites:
  - name: Sixstar STR
    url: https://sixstarstr.com
assignees:
  - dfoulger

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime-str
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Sixstar STR Status
  introTitle: Sixstar STR Status
  introMessage: 

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
